name: Deploy Backend

on:
  push:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4
      
      - name: Sync repo to production folder
        run: |
          rsync -av --delete --exclude '.env' . /root/revamp_app/backend

      - name: Deploy backend
        run: |
          cd /root/revamp_app
          docker compose build backend
          docker compose up -d backend
